from yacs.config import CfgNode as CN

_C = CN()

_C.MODEL = CN()
_C.MODEL.DEVICE = 'cuda'
_C.MODEL.SCALE_FACTOR = 16
_C.MODEL.GEN_ACTIVATION = 'prelu'
_C.MODEL.DIS_ACTIVATION = 'lrelu'
_C.MODEL.GEN_NORM = 'none'
_C.MODEL.DIS_NORM = 'spectral'
_C.MODEL.NUM_STAGES = 10
_C.MODEL.EDGE = False
_C.MODEL.UPSAMPLE_MODE = 'deconv'
_C.MODEL.BASE_MODEL_NAME = 'dbpn-ll'
_C.MODEL.SE_MODULE = False
_C.MODEL.INCEPTION_MODULE = False
_C.MODEL.INIT_UNET = False
_C.MODEL.RECONSTRUCTION = False
_C.MODEL.BICUBIC_RESIDUAL = False

_C.SOLVER = CN()
_C.SOLVER.BATCH_SIZE = 8
_C.SOLVER.MAX_ITER = 1000000
_C.SOLVER.GENERATOR_OPTIM = 'adam'
_C.SOLVER.GENERATOR_LR = 1e-4
_C.SOLVER.GENERATOR_BETA1 = 0.9
_C.SOLVER.GENERATOR_BETA2 = 0.999
_C.SOLVER.GENERATOR_EPS = 1e-8
_C.SOLVER.DISCRIMINATOR_OPTIM = 'adam'
_C.SOLVER.DISCRIMINATOR_LR = 1e-4
_C.SOLVER.DISCRIMINATOR_BETA1 = 0.9
_C.SOLVER.DISCRIMINATOR_BETA2 = 0.999
_C.SOLVER.DISCRIMINATOR_EPS = 1e-8
_C.SOLVER.TRAIN_GAN_START = 10000
_C.SOLVER.GEN_TRAIN_RATIO = 1
_C.SOLVER.DIS_TRAIN_RATIO = 1

_C.SOLVER.RECONLOSS_WEIGHT = 1.0
_C.SOLVER.VGGLOSS_WEIGHT = 1.0
_C.SOLVER.GANLOSS_WEIGHT = 0.001
_C.SOLVER.STYLELOSS_WEIGHT = 0.001
_C.SOLVER.VARIATION_REG_WEIGHT = 0.001
_C.SOLVER.GRADIENT_PENALTY_WEIGHT = 0

_C.SOLVER.GANLOSS_FN = 'BCE'
_C.SOLVER.GEN_L1 = True
_C.SOLVER.RECONSTRUCTION_LOSS = True
_C.SOLVER.VGG_LOSS = False
_C.SOLVER.GEN_VGG = 'before'
_C.SOLVER.STYLE_LOSS = False
_C.SOLVER.VARIATION_REGURALIZATION = False
_C.SOLVER.DISCRIMINATOR_TYPE = ('UNet',)

_C.SOLVER.MIXUP = False
_C.SOLVER.L1MOVE = 0
_C.SOLVER.FOCAL_GAMMA = 0

_C.SOLVER.BLUR_AUG = False

_C.SCHEDULER = CN()
_C.SCHEDULER.GENERATOR = False
_C.SCHEDULER.GENERATOR_STEP = 10000
_C.SCHEDULER.GENERATOR_GAMMA = 0.1
_C.SCHEDULER.DISCRIMINATOR = False
_C.SCHEDULER.DISCRIMINATOR_STEP = 10000
_C.SCHEDULER.DISCRIMINATOR_GAMMA = 0.1
_C.SCHEDULER.RECONLOSS = False
_C.SCHEDULER.RECONLOSS_STEP = 5000
_C.SCHEDULER.RECONLOSS_GAMMA = 0.95

_C.INPUT = CN()
_C.INPUT.PATCH_SIZE = 32

_C.DATASETS = CN()
_C.DATASETS.TRAIN = ('div8k_train',)
_C.DATASETS.EVAL = ('div8k_minival',)
_C.DATASETS.TEST = ('div8k_test',)
# _C.DATASETS.TEST = ('div8k_val',)
_C.DATASETS.VIS = ('div8k_minitrain',)

_C.OUTPUT_DIR = 'output'
_C.PRETRAIN_MODEL = 'weights/base_model.pth'
_C.PRETRAIN_D_MODEL = ''
_C.SEED = 123

_C.DEBUG = CN()
_C.DEBUG.SKIP_SAVE_IMAGE = True
_C.DEBUG.PRINT = False
_C.DEBUG.WRITE = False
_C.DEBUG.GEN = False